---
title: "Shiny Tutorial"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}

# Shiny
library(flexdashboard)
library(shiny)
library(shinyWidgets)
library(DT)

# Core
library(tidyverse)
library(lubridate)
library(plotly)


# Spatial Data
library(raster)
library(sf)


# Currency formatting
source("00_scripts/plot_sales.R")
```

```{r}

# Bike data
bikes_tbl      <- readRDS("Data/bikes_tbl.rds")
bikeshops_tbl  <- readRDS("Data/bikeshops_tbl.rds")
orderlines_tbl <- readRDS("Data/orderlines_tbl.rds")

bike_orderlines_tbl <- orderlines_tbl %>%
    left_join(bikes_tbl,     by = c("product_id" = "bike_id")) %>%
    left_join(bikeshops_tbl, by = c("customer_id" = "bikeshop_id")) %>%
    mutate(total_price = price_euro * quantity)

# German spatial data
germany_sp <- getData('GADM', country='DE', level=1) 
germany_sf <- st_as_sf(germany_sp) %>% 
  
                  # Add english names
                  mutate(VARNAME_1 = ifelse(is.na(VARNAME_1), NAME_1, VARNAME_1)) 


```




Sidebar {.sidebar}
------------------------

```{r}
# Inputs

checkboxGroupInput(inputId = "checkbox_group_bike", 
                   label   = h4("Bike Type"), 
                   choices = c("Mountain" = "Mountain",
                               "Road"       = "Road",
                               "E-Bikes"     = "E-Bikes",
                               "Hybrid/City" = "Hybrid / City",
                               "Gravel" = "Gravel"), 
                   selected = c("Mountain"))


dateRangeInput(inputId = "date_range", 
               label   = h4("Date Range"), 
               start   = min(bike_orderlines_tbl$order_date), 
               end     = max(bike_orderlines_tbl$order_date),           
               min     = min(bike_orderlines_tbl$order_date), 
               max     = max(bike_orderlines_tbl$order_date),
               format = "yyyy-mm-dd",
               startview = "year")

sliderInput(inputId = "slider_input", 
            label   = h4("Slider Range"), 
            min     = min(bike_orderlines_tbl$price_euro),
            max     = max(bike_orderlines_tbl$price_euro), 
            value   = c(1000, 3000), 
            step    = 100, 
            round   = TRUE, 
            pre     = "€")

pickerInput(inputId = "picker_input",
            label = "Bike Family", 
            choices = c("Adventure", "All-Road", "City", "Cross-Country","Cyclocross","Dirt Jump","Downhill",
            "E-City","E-Fitness","E-Gravel","E-Mountain","E-Trekking","Endurance","Enduro",
            "Fat Bikes","Race","Touring","Trail","Triathlon Bike"),
            multiple = TRUE,
            selected = c("Adventure"),
            options = list(title = "Bike Family"))
```


```{r}
# Reset Button
actionButton(inputId = "reset", 
             label   = "Reset", 
             icon    = icon("sync"))

observeEvent(eventExpr = input$reset, handlerExpr = {
  
  updateCheckboxGroupInput(session  = session, 
                           inputId  = "checkbox_group_bike", 
                           selected = c("Mountain"))
  
  updateDateRangeInput(session = session, 
                       inputId = "date_range", 
                       start   = min(bike_orderlines_tbl$order_date), 
                       end     = max(bike_orderlines_tbl$order_date))
  
  updateSliderInput(session = session, 
                    inputId = "slider_input", 
                    value   = c(1000, 7000))
  
  updatePickerInput(session = session,
                    inputID = "picker_input",
                    selected = c())

  
})
```


```{r}
#Section - Checkbox Output Bike
output$checkbox_values_bike <- renderPrint(input$checkbox_group_bike)

textOutput(outputId = "checkbox_values_bike")
```

```{r}
# Section - Picker Output Bike
output$picker_values_bike <- renderPrint(input$picker_input)

textOutput(outputId = "picker_values_bike")
```

```{r}
# Section - Date Range
output$date_range_values <- renderPrint(input$date_range)

textOutput(outputId = "date_range_values")
```

```{r}
# Section - Slider Output
output$slider_values <- renderPrint(input$slider_input)

textOutput(outputId = "slider_values")
```



Column {data-width=750}
---------------------------------------------------------------

### By State

```{r}
# filter bike_orderlines_tbl reactive
bike_orderlines_tbl_filtered <- reactive({bike_orderlines_tbl %>% 
                  filter(order_date >= input$date_range[1],
                         order_date <= input$date_range[2],
                         price_euro >= input$slider_input[1],
                         price_euro <= input$slider_input[2],
                         category_1 %in% input$checkbox_group_bike,
                         category_2 %in% input$picker_input)})
```

```{r}
# groub by state
geo_plot_tbl <- reactive({bike_orderlines_tbl_filtered() %>% group_by(state)%>%
                  summarise(total_revenue = sum(total_price)) %>%
                  ungroup() %>%
                  right_join(germany_sf, by = c("state" = "VARNAME_1")) %>% 
                  mutate(total_revenue = ifelse(is.na(total_revenue), 0, total_revenue)) %>% 
                  mutate(label_text = str_glue("State: {state}
                                         Revenue: {format_to_euro(total_revenue)}")) %>% 
                  st_as_sf()})
```


```{r}
# Plot
geoPlot <- reactive({plot_ly(geo_plot_tbl(), 
                             split      = ~NAME_1, 
                             color      = ~total_revenue,
                             colors     = "Blues",
                             stroke     = I("black"),
                             hoverinfo  = 'text', 
                             text       = ~label_text, 
                             hoveron    = "fills", 
                             showlegend = FALSE)})
```

```{r}
# Render Plot
renderPlotly(geoPlot())
```



Column {data-width=150}
-----------------------

### Section - Sales Plots
```{r}
radioGroupButtons(
   inputId = "radio_Group_Buttons",
   label = "Time Unit", 
    choices = c("W" = "weekly",
                "M" = "month",
                "Q" = "quarter"),
   status = "primary"
)

```

Column {data-width=750}
-----------------------
### Sales

```{r}
# reactive table
filtered_tbl <- reactive({
  bike_orderlines_tbl %>%
    filter(order_date >= input$date_range[1],
           order_date <= input$date_range[2],
           price_euro >= input$slider_input[1],
           price_euro <= input$slider_input[2])     
})

# write bike type input as condition sting
bike_type_condition <- reactive({
  paste0("(", paste0(input$bike_type, collapse = "|"), ")")
})

# write bike family input as condition sting
bike_family_condition <- reactive({
  paste0("(", paste0(input$bike_family, collapse = "|"), ")")
})

# write time duration input as condition sting
time_condition <- reactive({
  paste0("(", paste0(input$radio_Group_Buttons, collapse = "|"), ")")
})

# reactive plot
category_plot <- reactive({plot_categories(filtered_tbl(),
                category_1 = bike_type_condition(), 
                category_2 = bike_family_condition(),
                unit = "month",
                ncol = 1, 
                scales = "free_y", 
                date_format = "%Y-%m-%d",
                interactive = TRUE)})

# render plot
renderPlotly(category_plot())
```

 
